name: Добавить рецепт
description: Заполните форму, а мы опубликуем ваш рецепт.
title: "Новый рецепт:"
labels: ["Новый рецепт"]
body:
  - type: textarea
    id: situation
    attributes:
      label: Ситуация, когда пригодится рецепт
      description: Это может быть описание типичной рутины в работе руководителя, дизайнера или редактора.
      value: Допустим, вы редактор и хотите...
    validations:
      required: false
  - type: textarea
    id: steps
    attributes:
      label: Как сделать
      description: Список шагов, которые помогут пользователю решить задачу. В разделе обязательно должен быть промт — запрос к нейросети.
      value: | 
        1. Открыть [ЧатГПТ](https://chat.openai.com).
        2. Ввести промт:
        ```
        Собери данные о городах Европы.
        Покажи их в виде таблицы.
        ```
    validations:
      required: false
  - type: textarea
    id: result
    attributes:
      label: Результат
      description: Покажите результат на скриншоте. Можно оставить ссылку или перетащить файл скриншота в поле ввода.
      placeholder: Ссылка на скриншот
    validations:
      required: false
  - type: textarea
    id: danger
    attributes:
      label: Что может пойти не так
      description: На что пользователю обратить особое внимание? Что может пойти не так?.
      value: Если сделать X, то все исчезнет.
    validations:
      required: false
